### ISSUE TITLE
Write to file error

### ISSUE THREAD

**Issue by suenalaba** [suenalaba/ped#6]
Data not being saved? 

![f40c6707706a166bc5ae78b6aac0de77.png](https://raw.githubusercontent.com/suenalaba/ped/main/files/729e9474-f390-4ec3-bedd-01c8ade68632.png)

**Comment by chooyikai** [comment]
Hello, can you provide more details (e.g. OS, whether or not you had the data files open in a different program when trying to save, etc)? Several of my team members have tested this separately on both Windows 10 and MacOS and we are unable to reproduce this bug (and the other data loading bug).
